;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        evil-next-line
        evil-normal-state
        evil-previous-line
        kill-sexp
        mark-sexp
        sp-raise-sexp
        whole-line-or-region-kill-ring-save
        ))

(setq mc/cmds-to-run-once
      '(
        evil-change
        lsp-ui-doc--handle-mouse-movement
        npm-mode-npm-run
        ))
